### ISSUE TITLE
Support spawnSync

### ISSUE THREAD

**Issue by BigstickCarpet** [IndigoUnited/node-cross-spawn#11]
Node 0.12 now has [`spawnSync`](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) in addition to `spawn`.   It would be great it node-cross-spawn supported this new method.

**Comment by satazor** [comment]
Yeah this would be actually easy to do. We could simply add a .sync method. Can you do a PR?

**Comment by satazor** [comment]
Merged and landed in `0.3.0`. Thanks for the PR, it was perfect!
