### ISSUE TITLE
Setup Windows CI

### ISSUE THREAD

**Issue by Glavin001** [IndigoUnited/node-cross-spawn#17]
Travis CI does not support Windows, although how about [AppVeyor](http://www.appveyor.com/)?

Any other reason why there isn't a Windows CI setup for this project already?

**Comment by satazor** [comment]
Didn't had the time to find a solution. AppVeyor looks interesting though. Will look at it.

**Comment by Glavin001** [comment]
I am going to add AppVeyor for Windows testing in my Pull Request for #16.

**Comment by satazor** [comment]
@Glavin001 this is done! working great so far.
