### ISSUE TITLE
Extract an async only version

### ISSUE THREAD

**Issue by johanneswuerbach** [IndigoUnited/node-cross-spawn#19]
As this module is shipped with ember-cli and several ember-cli users have issues to compile native c extensions it would be nice to have the async version available as a separate module

Related: https://github.com/IndigoUnited/node-cross-spawn/pull/18

**Comment by satazor** [comment]
I would prefer to do the inverse and create a sync version separately.

**Comment by johanneswuerbach** [comment]
I'm fine with both and can look into it when I have some free minutes.

**Comment by satazor** [comment]
Are you ok with this @BigstickCarpet ?

**Comment by BigstickCarpet** [comment]
As long as the major version number changes, it should be fine. The only bummer is that libraries which require _both_ the sync _and_ async functionality (like [Yeoman](https://www.npmjs.com/package/yeoman-generator)) will have to import two libraries instead of one. 

FYI - @kevva and @SBoudrias

**Comment by satazor** [comment]
Perhaps indeed the best solution is to separate the `async` only version and keep node-cross-spawn as it is. I'm working on this at the moment.

**Comment by SBoudrias** [comment]
We really didn't heard issues from user on our side having issue to compile native C.

Are you sure this is really an issue for a lot of your users?

**Comment by johanneswuerbach** [comment]
I'm not sure, but @stefanpenner knows more.

**Comment by stefanpenner** [comment]
> Are you sure this is really an issue for a lot of your users?

yes, pains are as follows:

1. [all] slow install times
2. [windows users] are limited to 255char paths for things that run in gyp
3. [windows users] without any compiler toolchain
4. users with a misconfigured compiler toolchain

* the second issue, can be a total non-starter.
* 3 and 4 are often affect users who really should not be required to be comfortable with compiler toolchains to use simple node tooling.

**Comment by satazor** [comment]
Done.

https://github.com/IndigoUnited/node-cross-spawn-async

**Comment by stefanpenner** [comment]
Thank you kindly :). :beers:

**Comment by kevva** [comment]
@SBoudrias, are we even using the sync stuff? Else we should use `node-cross-spawn-async`.
