### ISSUE TITLE
spawn.sync looks broke

### ISSUE THREAD

**Issue by SBoudrias** [IndigoUnited/node-cross-spawn#20]
We're having failing tests with yeoman generators. Here's a trace:

https://travis-ci.org/yeoman/generator-node/jobs/71051980

In the trace you can see we're using cross-spawn 1.0.3

**Comment by satazor** [comment]
Hey @SBoudrias 

The issue is with spawn-sync because it is using a fallback for node `0.10`.
Are you using stdio `inherit` anywhere? If so I've submitted a PR that fixes that here https://github.com/ForbesLindesay/spawn-sync/pull/26/files but they didn't land a release yet.

**Comment by SBoudrias** [comment]
@satazor Yes, that's exactly what we're doing (setting stdio to `inherit`).

**Comment by satazor** [comment]
Ok, I've seen that you asked them to release a new version.
I'll leave the issue open until its resolved.

**Comment by satazor** [comment]
Bumped patch to force re-download new version.
