### ISSUE TITLE
Failed to replace env in config: ${APPDATA}

### ISSUE THREAD

**Issue by NogsMPLS** [IndigoUnited/node-cross-spawn#23]
Running into a weird issue when I try to use cross-spawn to execute an npm command:

![appdata-error2](https://cloud.githubusercontent.com/assets/6899011/11103496/484213b0-8888-11e5-9412-8bcd369f7aeb.PNG)

This seems possibly related to: 

https://github.com/npm/npm/issues/7468
https://github.com/npm/npm/issues/2840

**Comment by satazor** [comment]
This looks like a npm problem, not a cross-spawn issue.. basically you have defined appdata in npmrc and not supplied a APPDATA env.
