### ISSUE TITLE
Unable to pipe stdout and stderr to a file

### ISSUE THREAD

**Issue by ramyaa** [IndigoUnited/node-cross-spawn#33]
Hi

I'm not able to pipe the stfout/err to a file. This is the sample im trying:

```
var spawn = require('cross-spawn),
    out = fs.openSync('run.log', 'a');
   var childProcess =   spawn('myserver', ['run'], {
      stdio: [ 'ignore', out, out ], // piping stdout and stderr to run.log
      detached: true
    });
    childProcess.unref();
    sleep(2300); // delay needed for the "myserver run" to start
    var run_output = fs.readFileSync(path.join(working_dir, 'run.log')).toString();
    expect(run_output).includes("listening on 100101");

```

On running this i see a new command prompt popping up, with the "listening on 100101" message.
And run.log is empty.

Ideally, I would expect it to just pipe the output to run.log and NOT bring up a new cmd prompt.

Could you please help me with this?

Im running it on 
```
Windows 10
"mocha": "^2.4.5"
```

Thanks
Ramya

**Comment by satazor** [comment]
You can't pass a regular stream to stdio, it doesn't work like that. You must manually call .pipe() on .stdout and .stderr. Sorry for the small response but I'm on the phone. Hope this answer leads you to the correct path

**Comment by satazor** [comment]
After investigating, your code looks correct and it should work.I'm currently investigating and it seems that NodeJS is doing some "hackery" with file descriptors when using `detached` that doesn't play well with `cmd.exe`.

**Comment by ramyaa** [comment]
Oh good! Thanks for looking into it! Will wait for your update.

**Comment by satazor** [comment]
@ramyaa could you try this with the v4.0.0 version? While not a definitive solution, it could have fixed your use-case.

**Comment by ramyaa** [comment]
Sure. will check and let you know the results.

**Comment by satazor** [comment]
Bump.

**Comment by ramyaa** [comment]
Hey sorry... was held up in a couple of other tasks.
Will update you in a couple of days for sure.

Thanks
Ramya

**Comment by satazor** [comment]
Closing this for now, feel free to comment whenever you get back to this.
