### ISSUE TITLE
Add `kill` function to spawn object

### ISSUE THREAD

**Issue by kentcdodds** [IndigoUnited/node-cross-spawn#40]
Originally I wanted to extract [this](https://github.com/mysticatea/npm-run-all/issues/59) as a separate module, but I think it actually makes most sense to simply add it to `cross-spawn` itself. Would you be interested? The [`win32`](https://github.com/mysticatea/npm-run-all/blob/master/src/lib/spawn-win32.js#L19-L26) version of the function would be:

```javascript
function kill() {
  crossSpawn("taskkill", ["/F", "/T", "/PID", this.pid])
}
```

And the [`posix`](https://github.com/mysticatea/npm-run-all/blob/master/src/lib/spawn-posix.js):

```javascript
const getDescendentProcessInfo = require("ps-tree")

function kill() {
    getDescendentProcessInfo(this.pid, (err, descendent) => {
        if (err) {
            return
        }

        descendent.forEach(({PID: pid}) => {
            try {
                process.kill(pid)
            }
            catch (_err) {
                // ignore.
            }
        })
    })
}
```

Would you be willing to accept a PR for this?

cc @mysticatea

**Comment by satazor** [comment]
I think this is out of the scope of this project and should be in its own module.

Thanks anyway.

**Comment by kentcdodds** [comment]
`cross-spawn-with-kill` coming soon to an npm near you :)
cc @mysticatea

**Comment by hemanth** [comment]
heh heh I came here exactly for this!

**Comment by kentcdodds** [comment]
It's a thing now :) https://github.com/kentcdodds/cross-spawn-with-kill

**Comment by satazor** [comment]
Cool

**Comment by Igmat** [comment]
@kentcdodds, thanks a lot for your package - it saves my day.
@satazor, are you sure that `kill()` for child processes is out of scope for your package? I've spent two days trying to figure out why my [integration test](https://github.com/kulshekhar/ts-jest/issues/32) doesn't work, cause I don't even thought that problem could be in your package. I have used your package in same manner as node's default `spawn` function and used [types from node](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/node/index.d.ts#L1433) for it. Could you please, rethink your decision and accept a PR for it, or may be add mention of this behavior in readme with link to [cross-spawn-with-kill](https://github.com/kentcdodds/cross-spawn-with-kill)?

**Comment by MohamedLamineAllal** [comment]
@satazor What's wrong with accepting the PR ?

**Comment by satazor** [comment]
You may read the thread starting at this comment on why it didn’t make it: https://github.com/moxystudio/node-cross-spawn/pull/44#issuecomment-343612282
