### ISSUE TITLE
Cross-spawn fails to run remove command on windows 

### ISSUE THREAD

**Issue by rollymaduk** [IndigoUnited/node-cross-spawn#49]
using the rm -rf [directorypath]  command on windows fails to recognize the command, any idea why? your help will be greatly appreciated. Nice project by the way!

**Comment by satazor** [comment]
The goal of this project is not to be able to give support for unix shell commands on Windows.

You might want to look at https://github.com/shelljs/shelljs

**Comment by rollymaduk** [comment]
Thanks a lot @satazor very helpful!
