### ISSUE TITLE
Is there a way to pipe to parent stdout and then save that output to a variable?

### ISSUE THREAD

**Issue by dewdad** [IndigoUnited/node-cross-spawn#50]
Meaning can I live log the child process but then save the out resulting output to a variable?

**Comment by satazor** [comment]
You can listen to the `data` events and print it and accumulate at the same time. Is that what you want?

**Comment by dewdad** [comment]
Can I do that with spawn.sync? Ideally that is what I'd like to do.

**Comment by satazor** [comment]
No you can't, only with the async version. Additionally if this is for unix only, you can take a look at `tee`.

**Comment by dewdad** [comment]
Thank you so much.

**Comment by satazor** [comment]
Just for curiosity, what did you end up doing to accomplish what you wanted?

**Comment by dewdad** [comment]
Exactly what you suggested using event emitters on the child process returned from the async call.

Thanks again.
