### ISSUE TITLE
don't check for windows, check for cmd

### ISSUE THREAD

**Issue by ForsakenHarmony** [IndigoUnited/node-cross-spawn#58]
https://github.com/IndigoUnited/node-cross-spawn/blob/master/lib/parse.js#L64

check the comspec enviroment variable
this way it prevents anyone trying to use something other than cmd on windows

**Comment by ForsakenHarmony** [comment]
you know what, fuck it

**Comment by satazor** [comment]
@ForsakenHarmony I didn't understand what you were trying to say. Anyway, npm is not flawed.. it's actually the best package manager around.

**Comment by ForsakenHarmony** [comment]
not npm itself, just support for anything other than cmd on windows
