### ISSUE TITLE
spawn inputs console warnings into stdout stream

### ISSUE THREAD

**Issue by joadr** [IndigoUnited/node-cross-spawn#70]
Hello,
I got here because I'm trying to convert pdf files to images using graphicsmagic. The thing is that PDF files exported with Microsoft word on Mac OS X, have some weird thing and the command of graphicsmagick throws a warning in the console. The issue here is that that warning printed in the console is attached to the stdout from this library causing that the resulting file is corrupted (has the warning in the beginning of the file). And I've found no way of fixing this issue. Any ideas?

**Comment by satazor** [comment]
Cross-spawn doesn't do anything soecial regarding stdout and stderr, it simply respects that. If that library is printing warnings into stdout, they are mixing output with logging. You should report that error to graphicsmagick instead.

**Comment by joadr** [comment]
Is there a way of adding > /dev/null at the end of the command in order to avoid the warning message? I do it in my computer and warning disappears and the file gets converted.

**Comment by satazor** [comment]
No, you would have to use child process exec instead. Could you provide the sample file, shell command and nosejs code so I can help you further?

**Comment by satazor** [comment]
Closing due to lack of feedback.
