### ISSUE TITLE
Support option to mirror exit status

### ISSUE THREAD

**Issue by AndersDJohnson** [IndigoUnited/node-cross-spawn#88]
Support an option to internally call `process.exit(result.status)`.

**Comment by satazor** [comment]
Is that something that Node.js does?

**Comment by satazor** [comment]
Closing because lack of feedback.

**Comment by AndersDJohnson** [comment]
I am not aware of such a feature in Node. Is 1:1 feature parity a goal here?

**Comment by satazor** [comment]
Yep, the goal is to be a drop-in replacement for nodejs spawn.

**Comment by satazor** [comment]
If you are looking for more high-level spawn/exec, I would suggest you to use https://github.com/sindresorhus/execa, which uses `cross-spawn` underneath.
